apiVersion: v2
name: custom-tls-ingress
description: Replace default OpenShift cluster ingress TLS certificate
type: application
version: 0.0.1
appVersion: "4.10.8" # Latest OpenShift version this was tested on
