apiVersion: v1
data:
  tls.crt: |
    {{- .Files.Get "tls/tls.crt" | nindent 4 }}
  tls.key: |
    {{- .Files.Get "tls/tls.key" | nindent 4 }}
kind: Secret
metadata:
  name: ingress-custom-tls
  namespace: openshift-ingress
type: kubernetes.io/tls
