apiVersion: v1
stringData:
  tls.crt: |
    {{- .Files.Get .Values.tls.certPath | nindent 4 }}
  tls.key: |
    {{- .Files.Get .Values.tls.keyPath | nindent 4 }}
kind: Secret
metadata:
  name: custom-ingress-tls
  namespace: openshift-ingress
type: kubernetes.io/tls
