apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: custom-ingress-tls
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: custom-ingress-tls
  patches:
    ingress-custom-tls:
      targetObjectRef:
        apiVersion: operator.openshift.io/v1
        kind: IngressController
        name: default
      patchTemplate: |
        spec:
          defaultCertificate:
            name: custom-ingress-tls
      patchType: application/merge-patch+json
