apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: custom-ingress-ca
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: custom-ingress-tls
  patches:
    ingress-custom-ca:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: Proxy
        name: cluster
      patchTemplate: |
        spec:
          trustedCA:
            name: custom-ingress-ca
      patchType: application/merge-patch+json
