apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: custom-ca
  namespace: openshift-config
spec:
  serviceAccountRef:
    name: default
  patches:
    custom-ca:
      targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: Proxy
        name: cluster
      patchTemplate: |
        spec:
          trustedCA:
            name: custom-ca
      patchType: application/merge-patch+json
